FROM registry.access.redhat.com/rhel7-atomic
MAINTAINER Veer Muchandi<veer@redhat.com>
RUN microdnf install -y --enablerepo=rhel-7-server-rpms --enablerepo=rhel-7-server-extras-rpms --enablerepo=rhel-7-server-optional-rpms \
automake gettext git lsof make tar unzip wget which && \
microdnf install -y --enablerepo=rhel-7-server-rpms --enablerepo=rhel-7-server-extras-rpms --enablerepo=rhel-7-server-optional-rpms java tomcat  && \
microdnf clean all -y && \
mkdir -p /opt/app-root && \
useradd -u 1001 -r -g 0 -d ${HOME} -s /sbin/nologin \
 -c "Default Application User" default && \
chown -R 1001:0 /opt/app-root
ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-2.b16.el7_4.x86_64
ENV CATALINA_HOME /usr/share/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH
EXPOSE 8080
USER tomcat
CMD systemctl start tomcat
